# Generated by Django 2.2.7 on 2019-12-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20191204_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
