# Generated by Django 2.2.7 on 2019-12-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='stories.Category'),
        ),
    ]
