# Generated by Django 2.2.7 on 2019-12-12 16:27

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='long_description',
            field=djrichtextfield.models.RichTextField(default='Long description', verbose_name='Long description'),
            preserve_default=False,
        ),
    ]
