# Generated by Django 2.2.7 on 2019-12-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='stories.Comment'),
        ),
    ]
